[alias]
wasm = "build --release --target wasm32-unknown-unknown"
schema = "run --example schema"
unit-test = "test"

[build]
rustflags = ["-C", "link-arg=-s"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=-reference-types,-bulk-memory"]
